export const LOAD_WEATHER_DETAILS = "LOAD_WEATHER_DETAILS";
export const LOAD_WEATHER_DETAILS_SUCCESS = 'LOAD_WEATHER_DETAILS_SUCCESS';
export const LOAD_WEATHER_DETAILS_FAILURE = 'LOAD_WEATHER_DETAILS_FAILURE';
export const UPDATE_WEATHER_DETAILS ="UPDATE_WEATHER_DETAILS";
export const SELECTED_DAY_DETAILS ='SELECTED_DAY_DETAILS';
