export const WeatherResponse = {
  data: [
    {
      weekNo: 1,
      weekDays: [
        {
          id: "01",
          title: "May 01",
          subTitle: 'SUNDAY, MAY 01',
          tempMax: "34°",
          tempMin: "28°",
          canBeRain: false,
          rangeId: 301,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '4.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "02",
          title: "May 02",
          subTitle: 'MONDAY, MAY 02',
          tempMax: "43°",
          tempMin: "23°",
          cloudDenses: "low",
          canBeRain: true,
          rangeId: 401,
          wind: 'SSE 5 mph',
          windGuts: '20mph',
          thunderStorm: '0%',
          cloudCover: "45%",
          Precipitation: '8.00',
          probPrecitation: '10%',
          humidity: '68%',
          dewPoint: "23°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "03",
          title: "May 03",
          tempMax: "42°",
          subTitle: 'TUESDAY, MAY 03',
          tempMin: "22°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 500,
          wind: 'ESE 7 mph',
          windGuts: '25mph',
          thunderStorm: '2%',
          cloudCover: "39%",
          Precipitation: '2.00',
          probPrecitation: '8%',
          humidity: '75%',
          dewPoint: "24°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "04",
          title: "May 04",
          subTitle: 'WEDNESDAY, MAY 04',
          tempMax: "41°",
          tempMin: "21°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 135,
          wind: 'SSE 5 mph',
          windGuts: '23mph',
          thunderStorm: '3%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '71%',
          dewPoint: "21°",
          sunDetails:
          {
            mSunSet: '6:18 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "05",
          title: "May 05",
          subTitle: 'THURSDAY, MAY 05',
          tempMax: "39°",
          tempMin: "19°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 444,
          wind: 'ESE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '2.00',
          probPrecitation: '6%',
          humidity: '72%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "06",
          title: "May 06",
          subTitle: 'FRIDAY, MAY 06',
          tempMax: "38°",
          tempMin: "18°",
          cloudDenses: "heavy",
          canBeRain: true,
          rangeId: 202,
          wind: 'SSE 3 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '3.00',
          probPrecitation: '9%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "07",
          title: "May 07",
          subTitle: 'SATURDAY, MAY 07',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "08",
          title: "May 08",
          subTitle: 'SUNDAY, MAY 08',
          tempMax: "34°",
          tempMin: "28°",
          canBeRain: false,
          rangeId: 301,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '4.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "09",
          title: "May 09",
          subTitle: 'MONDAY, MAY 09',
          tempMax: "43°",
          tempMin: "23°",
          cloudDenses: "low",
          canBeRain: true,
          rangeId: 401,
          wind: 'SSE 5 mph',
          windGuts: '20mph',
          thunderStorm: '0%',
          cloudCover: "45%",
          Precipitation: '8.00',
          probPrecitation: '10%',
          humidity: '68%',
          dewPoint: "23°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "10",
          title: "May 10",
          tempMax: "42°",
          subTitle: 'TUESDAY, MAY 10',
          tempMin: "22°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 500,
          wind: 'ESE 7 mph',
          windGuts: '25mph',
          thunderStorm: '2%',
          cloudCover: "39%",
          Precipitation: '2.00',
          probPrecitation: '8%',
          humidity: '75%',
          dewPoint: "24°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
      ],
    },
    {
      weekNo: 2,
      weekDays: [
        {
          id: "11",
          title: "May 11",
          subTitle: 'WEDNESDAY, MAY 11',
          tempMax: "34°",
          tempMin: "28°",
          canBeRain: false,
          rangeId: 301,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '4.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "12",
          title: "May 12",
          subTitle: 'THURSDAY, MAY 12',
          tempMax: "43°",
          tempMin: "23°",
          cloudDenses: "low",
          canBeRain: true,
          rangeId: 401,
          wind: 'SSE 5 mph',
          windGuts: '20mph',
          thunderStorm: '0%',
          cloudCover: "45%",
          Precipitation: '8.00',
          probPrecitation: '10%',
          humidity: '68%',
          dewPoint: "23°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "13",
          title: "May 13",
          tempMax: "42°",
          subTitle: 'FRIDAY, MAY 13',
          tempMin: "22°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 500,
          wind: 'ESE 7 mph',
          windGuts: '25mph',
          thunderStorm: '2%',
          cloudCover: "39%",
          Precipitation: '2.00',
          probPrecitation: '8%',
          humidity: '75%',
          dewPoint: "24°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "14",
          title: "May 14",
          subTitle: 'SATURDAY, MAY 14',
          tempMax: "41°",
          tempMin: "21°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 135,
          wind: 'SSE 5 mph',
          windGuts: '23mph',
          thunderStorm: '3%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '71%',
          dewPoint: "21°",
          sunDetails:
          {
            mSunSet: '6:18 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }

        },
        {
          id: "15",
          title: "May 15",
          subTitle: 'SUNDAY, MAY 15',
          tempMax: "39°",
          tempMin: "19°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 444,
          wind: 'ESE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '2.00',
          probPrecitation: '6%',
          humidity: '72%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "16",
          title: "May 16",
          subTitle: 'MONDAY, MAY 16',
          tempMax: "38°",
          tempMin: "18°",
          cloudDenses: "heavy",
          canBeRain: true,
          rangeId: 202,
          wind: 'SSE 3 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '3.00',
          probPrecitation: '9%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "17",
          title: "May 17",
          subTitle: 'TUESDAY, MAY 17',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }

        },
        {
          id: "18",
          title: "May 18",
          subTitle: 'WENDNESDAY, MAY 18',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "19",
          title: "May 19",
          subTitle: 'THURSDAY, MAY 19',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "20",
          title: "May 20",
          subTitle: 'TUESDAY, MAY 20',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
      ],
    },
    {
      weekNo: 3,
      weekDays: [
        {
          id: "21",
          title: "May 21",
          subTitle: 'WEDNESDAY, MAY 21',
          tempMax: "34°",
          tempMin: "28°",
          canBeRain: false,
          rangeId: 301,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '4.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "22",
          title: "May 22",
          subTitle: 'THURSDAY, MAY 22',
          tempMax: "43°",
          tempMin: "23°",
          cloudDenses: "low",
          canBeRain: true,
          rangeId: 401,
          wind: 'SSE 5 mph',
          windGuts: '20mph',
          thunderStorm: '0%',
          cloudCover: "45%",
          Precipitation: '8.00',
          probPrecitation: '10%',
          humidity: '68%',
          dewPoint: "23°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "23",
          title: "May 23",
          tempMax: "42°",
          subTitle: 'FRIDAY, MAY 23',
          tempMin: "22°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 500,
          wind: 'ESE 7 mph',
          windGuts: '25mph',
          thunderStorm: '2%',
          cloudCover: "39%",
          Precipitation: '2.00',
          probPrecitation: '8%',
          humidity: '75%',
          dewPoint: "24°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "24",
          title: "May 24",
          subTitle: 'SATURDAY, MAY 24',
          tempMax: "41°",
          tempMin: "21°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 135,
          wind: 'SSE 5 mph',
          windGuts: '23mph',
          thunderStorm: '3%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '71%',
          dewPoint: "21°",
          sunDetails:
          {
            mSunSet: '6:18 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }

        },
        {
          id: "25",
          title: "May 25",
          subTitle: 'SUNDAY, MAY 25',
          tempMax: "39°",
          tempMin: "19°",
          cloudDenses: "",
          canBeRain: false,
          rangeId: 444,
          wind: 'ESE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '2.00',
          probPrecitation: '6%',
          humidity: '72%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "26",
          title: "May 26",
          subTitle: 'MONDAY, MAY 26',
          tempMax: "38°",
          tempMin: "18°",
          cloudDenses: "heavy",
          canBeRain: true,
          rangeId: 202,
          wind: 'SSE 3 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '3.00',
          probPrecitation: '9%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "27",
          title: "May 27",
          subTitle: 'TUESDAY, MAY 27',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }

        },
        {
          id: "28",
          title: "May 28",
          subTitle: 'WENDNESDAY, MAY 28',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "29",
          title: "May 29",
          subTitle: 'THURSDAY, MAY 29',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
        {
          id: "30",
          title: "May 30",
          subTitle: 'TUESDAY, MAY 30',
          tempMax: "37°",
          tempMin: "17°",
          cloudDenses: "",
          canBeRain: true,
          rangeId: 501,
          wind: 'SSE 7 mph',
          windGuts: '23mph',
          thunderStorm: '0%',
          cloudCover: "41%",
          Precipitation: '5.00',
          probPrecitation: '6%',
          humidity: '78%',
          dewPoint: "28°",
          sunDetails:
          {
            mSunSet: '6:25 PM',
            mSunRise: '5:47 AM',
            eSunSet: '2:19 PM',
            eSunRise: '2:19 AM',
          }
        },
      ],
    }
  ]
};

